# Generated by Django 5.1.6 on 2025-02-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_image', models.ImageField(upload_to='upload/')),
                ('generated_image', models.ImageField(upload_to='generated/')),
            ],
        ),
    ]
